### ISSUE TITLE
Support in-memory keys in addition to key file

### ISSUE THREAD

**Issue by thomasbehr** [Ewert-Technologies/notarytool-kotlin#3]
It would be great, if `NotaryToolClient` accepted a `Supplier<ECKey>` or similar in addition to the key file location. This way the sensitive key data could be kept in secure storage like a [KeyStore](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/security/KeyStore.html) or similar instead of in a regular file.

**Comment by vewert** [comment]
I should have some time to work on this.

@thomasbehr could you provide a bit of code example of how you would envision using this with a `Supplier<ECKey>`?

**Comment by thomasbehr** [comment]
I've added patch that shows what worked for me. Hope it helps.
[key_supplier.patch](https://github.com/Ewert-Technologies/notarytool-kotlin/files/15147359/key_supplier.patch)

**Comment by vewert** [comment]
Thanks, I'll take a look at your patch.

**Comment by vewert** [comment]
@thomasbehr thanks again for your code samples. I decided to go with a more 'Kotlin-like' approach; instead of using a Java `Supplier<T>`, the constructor takes in a function that creates an `ECPrivateKey`. From Java, this can be called using a lambda.
